### ISSUE TITLE
Program logic control structures aren't working, find out why

### ISSUE THREAD

**Issue by Darthpbal** [Darthpbal/Sapphire-Tracker#20]

**Comment by Darthpbal** [comment]
### Error theory

'm thinking that it's possible that the program is fucking up at the parseGpsOrErr() method and it may be because the gps error variable that I'm using may be in the wrong scope. So then when I try to use it, and set it to something in the parseGpsOrErr() method, it may be losing that value when exiting the scope.

**Comment by Darthpbal** [comment]
## TODO
- [x]check that I have working GPS code.
- [x]encapsulate core group functions
- [ ]add parsing method to make individual vairables
- [ ]add parsing method to go straight to post string
- [ ]isolate encapsulated functions and test individually.
- [ ]incrementally combine encapsulated functions.

**Comment by Darthpbal** [comment]
### more detail
- [x] encaps GPS program
- [x] encap hppt program

## conclusion

it looks like I get some major data manipulation errors when I try to use a char\* on this gps data variable.  I should try to avoid that data type.
